
spring:
    datasource:
        url: jdbc:mysql://59.110.168.107:3306/test
        username: root
        password: uAiqwVwjJ8-i
        driver-class-name: com.mysql.jdbc.Driver
        
    data:
        elasticsearch:
            cluster-name: my-application
            cluster-nodes: 59.110.168.107:9300
    main:
        allow-bean-definition-overriding: true
#    security:
#        user:
#            name: syz
#            password: 123

rsocket:
    server:
         port=7000: 7000
         
mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    global-config:
        refresh-mapper: true
swagger:
    enabled: true
    
logging:
    level:
        com:
            syz:
                cli:
                    Dao: DEBUG
server:
    port: 8080
